title: Foundation Models and Biometrics
description: An overview of the recent advancements in foundation models, including such as Large Language Models (LLMs), Vision Language Models (VLMs), Audio-Language Models (ALMs), and Large Multi-modal Models (LMMs), with potential applications of these models in the field of biometrics. 
author: Hatef Otroshi

remote_theme: just-the-docs/just-the-docs
search_enabled: true